var annotated_dup =
[
    [ "DirektDSP", "namespaceDirektDSP.html", [
      [ "BuildContext", "structDirektDSP_1_1BuildContext.html", "structDirektDSP_1_1BuildContext" ],
      [ "BuiltNode", "structDirektDSP_1_1BuiltNode.html", "structDirektDSP_1_1BuiltNode" ],
      [ "BuiltSection", "structDirektDSP_1_1BuiltSection.html", "structDirektDSP_1_1BuiltSection" ],
      [ "ButtonDesc", "structDirektDSP_1_1ButtonDesc.html", "structDirektDSP_1_1ButtonDesc" ],
      [ "ClipIndicatorDesc", "structDirektDSP_1_1ClipIndicatorDesc.html", "structDirektDSP_1_1ClipIndicatorDesc" ],
      [ "ComboBoxDesc", "structDirektDSP_1_1ComboBoxDesc.html", "structDirektDSP_1_1ComboBoxDesc" ],
      [ "CustomDesc", "structDirektDSP_1_1CustomDesc.html", "structDirektDSP_1_1CustomDesc" ],
      [ "DirektAutoLayout", "classDirektDSP_1_1DirektAutoLayout.html", "classDirektDSP_1_1DirektAutoLayout" ],
      [ "DirektBaseEditor", "classDirektDSP_1_1DirektBaseEditor.html", "classDirektDSP_1_1DirektBaseEditor" ],
      [ "DirektClipIndicator", "classDirektDSP_1_1DirektClipIndicator.html", "classDirektDSP_1_1DirektClipIndicator" ],
      [ "DirektComboBox", "classDirektDSP_1_1DirektComboBox.html", "classDirektDSP_1_1DirektComboBox" ],
      [ "DirektComponentRegistry", "classDirektDSP_1_1DirektComponentRegistry.html", "classDirektDSP_1_1DirektComponentRegistry" ],
      [ "DirektFlexContainer", "classDirektDSP_1_1DirektFlexContainer.html", "classDirektDSP_1_1DirektFlexContainer" ],
      [ "DirektFooter", "classDirektDSP_1_1DirektFooter.html", "classDirektDSP_1_1DirektFooter" ],
      [ "DirektHeader", "classDirektDSP_1_1DirektHeader.html", "classDirektDSP_1_1DirektHeader" ],
      [ "DirektKnob", "classDirektDSP_1_1DirektKnob.html", "classDirektDSP_1_1DirektKnob" ],
      [ "DirektLabel", "classDirektDSP_1_1DirektLabel.html", "classDirektDSP_1_1DirektLabel" ],
      [ "DirektLookAndFeel", "classDirektDSP_1_1DirektLookAndFeel.html", "classDirektDSP_1_1DirektLookAndFeel" ],
      [ "DirektMacroControl", "classDirektDSP_1_1DirektMacroControl.html", "classDirektDSP_1_1DirektMacroControl" ],
      [ "DirektMeter", "classDirektDSP_1_1DirektMeter.html", "classDirektDSP_1_1DirektMeter" ],
      [ "DirektModuleBypassSoloStrip", "classDirektDSP_1_1DirektModuleBypassSoloStrip.html", "classDirektDSP_1_1DirektModuleBypassSoloStrip" ],
      [ "DirektParameterHistory", "classDirektDSP_1_1DirektParameterHistory.html", "classDirektDSP_1_1DirektParameterHistory" ],
      [ "DirektPopupPanel", "classDirektDSP_1_1DirektPopupPanel.html", "classDirektDSP_1_1DirektPopupPanel" ],
      [ "DirektPresetBrowser", "classDirektDSP_1_1DirektPresetBrowser.html", "classDirektDSP_1_1DirektPresetBrowser" ],
      [ "DirektSection", "classDirektDSP_1_1DirektSection.html", "classDirektDSP_1_1DirektSection" ],
      [ "DirektStereoMeter", "classDirektDSP_1_1DirektStereoMeter.html", "classDirektDSP_1_1DirektStereoMeter" ],
      [ "DirektTabPanel", "classDirektDSP_1_1DirektTabPanel.html", "classDirektDSP_1_1DirektTabPanel" ],
      [ "DirektToggle", "classDirektDSP_1_1DirektToggle.html", "classDirektDSP_1_1DirektToggle" ],
      [ "DividerDesc", "structDirektDSP_1_1DividerDesc.html", "structDirektDSP_1_1DividerDesc" ],
      [ "HBoxDesc", "structDirektDSP_1_1HBoxDesc.html", "structDirektDSP_1_1HBoxDesc" ],
      [ "KnobDesc", "structDirektDSP_1_1KnobDesc.html", "structDirektDSP_1_1KnobDesc" ],
      [ "LabelDesc", "structDirektDSP_1_1LabelDesc.html", "structDirektDSP_1_1LabelDesc" ],
      [ "MacroControlTarget", "structDirektDSP_1_1MacroControlTarget.html", "structDirektDSP_1_1MacroControlTarget" ],
      [ "MacroDesc", "structDirektDSP_1_1MacroDesc.html", "structDirektDSP_1_1MacroDesc" ],
      [ "MacroKnobDesc", "structDirektDSP_1_1MacroKnobDesc.html", "structDirektDSP_1_1MacroKnobDesc" ],
      [ "MacroTarget", "structDirektDSP_1_1MacroTarget.html", "structDirektDSP_1_1MacroTarget" ],
      [ "MacroTargetDesc", "structDirektDSP_1_1MacroTargetDesc.html", "structDirektDSP_1_1MacroTargetDesc" ],
      [ "MeterDesc", "structDirektDSP_1_1MeterDesc.html", "structDirektDSP_1_1MeterDesc" ],
      [ "NodeDescriptor", "structDirektDSP_1_1NodeDescriptor.html", null ],
      [ "NodeProps", "structDirektDSP_1_1NodeProps.html", "structDirektDSP_1_1NodeProps" ],
      [ "ParamSlot", "structDirektDSP_1_1ParamSlot.html", "structDirektDSP_1_1ParamSlot" ],
      [ "PluginConfig", "structDirektDSP_1_1PluginConfig.html", "structDirektDSP_1_1PluginConfig" ],
      [ "RadioGroupDesc", "structDirektDSP_1_1RadioGroupDesc.html", "structDirektDSP_1_1RadioGroupDesc" ],
      [ "SectionDesc", "structDirektDSP_1_1SectionDesc.html", "structDirektDSP_1_1SectionDesc" ],
      [ "SectionDescriptor", "structDirektDSP_1_1SectionDescriptor.html", "structDirektDSP_1_1SectionDescriptor" ],
      [ "SizeHint", "structDirektDSP_1_1SizeHint.html", "structDirektDSP_1_1SizeHint" ],
      [ "SliderDesc", "structDirektDSP_1_1SliderDesc.html", "structDirektDSP_1_1SliderDesc" ],
      [ "SpacerDesc", "structDirektDSP_1_1SpacerDesc.html", "structDirektDSP_1_1SpacerDesc" ],
      [ "StereoMeterDesc", "structDirektDSP_1_1StereoMeterDesc.html", "structDirektDSP_1_1StereoMeterDesc" ],
      [ "TabDesc", "structDirektDSP_1_1TabDesc.html", "structDirektDSP_1_1TabDesc" ],
      [ "TabPanelDesc", "structDirektDSP_1_1TabPanelDesc.html", "structDirektDSP_1_1TabPanelDesc" ],
      [ "ToggleDesc", "structDirektDSP_1_1ToggleDesc.html", "structDirektDSP_1_1ToggleDesc" ],
      [ "VBoxDesc", "structDirektDSP_1_1VBoxDesc.html", "structDirektDSP_1_1VBoxDesc" ],
      [ "XYPadDesc", "structDirektDSP_1_1XYPadDesc.html", "structDirektDSP_1_1XYPadDesc" ]
    ] ],
    [ "Service", "namespaceService.html", [
      [ "PresetManager", "classService_1_1PresetManager.html", "classService_1_1PresetManager" ],
      [ "PresetMetadata", "structService_1_1PresetMetadata.html", "structService_1_1PresetMetadata" ]
    ] ]
];