DirektDSP GUI: DirektDSP::DirektParameterHistory Class Reference
DirektDSP::DirektParameterHistory Class Reference
Maintains undo/redo history for APVTS parameter edits.
#include <DirektParameterHistory.h>
Classes
struct ParameterChange
Public Member Functions
void pushChange (const juce::String &paramID, float oldValueNormalized, float newValueNormalized)
Adds a committed parameter edit to history.
bool canUndo () const noexcept
Returns true when at least one undo step is available.
bool canRedo () const noexcept
Returns true when at least one redo step is available.
bool undo (juce::AudioProcessorValueTreeState &apvts)
Applies the previous history step.
bool redo (juce::AudioProcessorValueTreeState &apvts)
Re-applies the next history step.
Private Member Functions
bool applyValue (juce::AudioProcessorValueTreeState &apvts, const ParameterChange &change, bool applyNewValue)
Private Attributes
std::vector< ParameterChange > history
size_t cursor = 0
Number of steps currently applied.
Detailed Description
Maintains undo/redo history for APVTS parameter edits.
History entries store parameter IDs plus normalized start/end values. Undo/redo applies values via setValueNotifyingHost() so host state stays in sync.
Definition at line 15 of file DirektParameterHistory.h.
Member Function Documentation
applyValue()
bool DirektDSP::DirektParameterHistory::applyValue (juce::AudioProcessorValueTreeState & apvts, const ParameterChange & change, bool applyNewValue) private
Definition at line 67 of file DirektParameterHistory.cpp.
References DirektDSP::DirektParameterHistory::ParameterChange::newValueNormalized, DirektDSP::DirektParameterHistory::ParameterChange::oldValueNormalized, and DirektDSP::DirektParameterHistory::ParameterChange::paramID.
Referenced by redo(), and undo().
canRedo()
bool DirektDSP::DirektParameterHistory::canRedo () const noexcept
Returns true when at least one redo step is available.
Definition at line 28 of file DirektParameterHistory.cpp.
References cursor, and history.
Referenced by redo().
canUndo()
bool DirektDSP::DirektParameterHistory::canUndo () const noexcept
Returns true when at least one undo step is available.
Definition at line 23 of file DirektParameterHistory.cpp.
References cursor.
Referenced by undo().
pushChange()
void DirektDSP::DirektParameterHistory::pushChange (const juce::String & paramID, float oldValueNormalized, float newValueNormalized)
Adds a committed parameter edit to history.
Parameters
paramID Parameter identifier in APVTS.
oldValueNormalized Previous normalized value in range [0, 1].
newValueNormalized New normalized value in range [0, 1].
Definition at line 6 of file DirektParameterHistory.cpp.
References cursor, and history.
Referenced by DirektDSP::DirektKnob::commitChange(), DirektDSP::DirektComboBox::DirektComboBox(), and DirektDSP::DirektToggle::DirektToggle().
redo()
bool DirektDSP::DirektParameterHistory::redo (juce::AudioProcessorValueTreeState & apvts)
Re-applies the next history step.
Parameters
apvts Target state containing parameters.
Returns
true when a step was applied.
Definition at line 50 of file DirektParameterHistory.cpp.
References applyValue(), canRedo(), cursor, and history.
Referenced by DirektDSP::DirektBaseEditor::keyPressed().
undo()
bool DirektDSP::DirektParameterHistory::undo (juce::AudioProcessorValueTreeState & apvts)
Applies the previous history step.
Parameters
apvts Target state containing parameters.
Returns
true when a step was applied.
Definition at line 33 of file DirektParameterHistory.cpp.
References applyValue(), canUndo(), cursor, and history.
Referenced by DirektDSP::DirektBaseEditor::keyPressed().
Member Data Documentation
cursor
size_t DirektDSP::DirektParameterHistory::cursor = 0 private
Number of steps currently applied.
Definition at line 64 of file DirektParameterHistory.h.
Referenced by canRedo(), canUndo(), pushChange(), redo(), and undo().
history
std::vector<ParameterChange> DirektDSP::DirektParameterHistory::history private
Definition at line 63 of file DirektParameterHistory.h.
Referenced by canRedo(), pushChange(), redo(), and undo().
The documentation for this class was generated from the following files:
core/DirektParameterHistory.h
core/DirektParameterHistory.cpp