DirektDSP GUI: DirektDSP::DirektHeader Class Reference
DirektDSP::DirektHeader Class Reference
#include <DirektHeader.h>
Public Member Functions
DirektHeader (juce::String pluginName, juce::Colour accentColour, Service::PresetManager &presetManager, juce::AudioProcessorValueTreeState &)
void paint (juce::Graphics &g) override
void resized () override
void mouseDown (const juce::MouseEvent &e) override
void updatePresetName ()
Public Attributes
std::function< void()> onPresetLabelClicked
Private Attributes
juce::String pluginName
juce::Colour accent
juce::TextButton prevBtn {"<"}
juce::TextButton nextBtn {">"}
juce::Label presetLabel
Service::PresetManager & presetManager
Detailed Description
Definition at line 17 of file DirektHeader.h.
Constructor & Destructor Documentation
DirektHeader()
DirektDSP::DirektHeader::DirektHeader (juce::String pluginName, juce::Colour accentColour, Service::PresetManager & presetManager, juce::AudioProcessorValueTreeState &)
Definition at line 10 of file DirektHeader.cpp.
References DirektDSP::Colours::bgHeader, Service::PresetManager::loadNextPreset(), Service::PresetManager::loadPreviousPreset(), nextBtn, presetLabel, prevBtn, DirektDSP::Colours::textBright, DirektDSP::Colours::textDim, and updatePresetName().
Member Function Documentation
mouseDown()
void DirektDSP::DirektHeader::mouseDown (const juce::MouseEvent & e) override
Definition at line 75 of file DirektHeader.cpp.
References onPresetLabelClicked, and presetLabel.
paint()
void DirektDSP::DirektHeader::paint (juce::Graphics & g) override
Definition at line 42 of file DirektHeader.cpp.
References accent, DirektDSP::Colours::bgHeader, DirektDSP::Colours::divider, pluginName, and DirektDSP::Colours::textDim.
resized()
void DirektDSP::DirektHeader::resized () override
Definition at line 64 of file DirektHeader.cpp.
References nextBtn, presetLabel, and prevBtn.
updatePresetName()
void DirektDSP::DirektHeader::updatePresetName ()
Definition at line 83 of file DirektHeader.cpp.
References Service::PresetManager::getCurrentPreset(), presetLabel, and presetManager.
Referenced by DirektHeader(), and DirektDSP::DirektBaseEditor::initCommon().
Member Data Documentation
accent
juce::Colour DirektDSP::DirektHeader::accent private
Definition at line 33 of file DirektHeader.h.
Referenced by paint().
nextBtn
juce::TextButton DirektDSP::DirektHeader::nextBtn {">"} private
Definition at line 36 of file DirektHeader.h.
Referenced by DirektHeader(), and resized().
onPresetLabelClicked
std::function<void()> DirektDSP::DirektHeader::onPresetLabelClicked
Definition at line 29 of file DirektHeader.h.
Referenced by DirektDSP::DirektBaseEditor::initCommon(), and mouseDown().
pluginName
juce::String DirektDSP::DirektHeader::pluginName private
Definition at line 32 of file DirektHeader.h.
Referenced by paint().
presetLabel
juce::Label DirektDSP::DirektHeader::presetLabel private
Definition at line 37 of file DirektHeader.h.
Referenced by DirektHeader(), mouseDown(), resized(), and updatePresetName().
presetManager
Service::PresetManager& DirektDSP::DirektHeader::presetManager private
Definition at line 39 of file DirektHeader.h.
Referenced by updatePresetName().
prevBtn
juce::TextButton DirektDSP::DirektHeader::prevBtn {"<"} private
Definition at line 35 of file DirektHeader.h.
Referenced by DirektHeader(), and resized().
The documentation for this class was generated from the following files:
chrome/DirektHeader.h
chrome/DirektHeader.cpp