DirektDSP GUI: DirektDSP::DirektBaseEditor Class Reference
DirektDSP::DirektBaseEditor Class Reference
#include <DirektBaseEditor.h>
Public Member Functions
DirektBaseEditor (juce::AudioProcessor &processor, juce::AudioProcessorValueTreeState &apvts, Service::PresetManager &presetManager, const PluginConfig &config, const NodeDescriptor &rootDescriptor)
DirektBaseEditor (juce::AudioProcessor &processor, juce::AudioProcessorValueTreeState &apvts, Service::PresetManager &presetManager, const juce::String &pluginName, juce::Colour accentColour, float aspectRatio, int defaultWidth, const std::vector< SectionDescriptor > &sectionDescriptors)
~DirektBaseEditor () override
void paint (juce::Graphics &g) override
void resized () override
bool keyPressed (const juce::KeyPress &key) override
Handles editor-local undo/redo shortcuts for parameter edits.
juce::Component * findComponentByID (const juce::String &id) const
void bindMeterSource (const juce::String &sourceID, const std::atomic< float > *source)
Protected Member Functions
virtual void layoutCustomSections (juce::Rectangle< int > mainArea)
virtual void paintCustomBackground (juce::Graphics &g, juce::Rectangle< int > mainArea)
DirektSection * findSection (const juce::String &title)
void showPopup (const juce::String &title, juce::Component *content, int w, int h)
void hidePopup ()
Protected Attributes
juce::AudioProcessorValueTreeState & apvts
std::vector< BuiltSection > builtSections
Private Member Functions
void initCommon (const juce::String &, juce::Colour accentColour, float ratio, int, int minWidth, int maxWidth, bool showHeader, bool showFooter, bool resizable, bool showTooltips)
void configureCrashRecovery (const juce::String &pluginName)
void saveCrashRecoverySnapshot () const
void restoreCrashRecoveryIfNeeded ()
void timerCallback () override
Private Attributes
DirektLookAndFeel lookAndFeel
DirektHeader header
DirektFooter footer
DirektPopupPanel popup
std::unique_ptr< juce::TooltipWindow > tooltipWindow
juce::ComponentBoundsConstrainer constrainer
std::unique_ptr< juce::ResizableCornerComponent > resizer
float aspectRatio {}
Service::PresetManager & presetManager
std::unique_ptr< DirektPresetBrowser > presetBrowser
bool configDriven = false
DirektParameterHistory parameterHistory
BuiltNode rootBuiltNode
std::vector< std::unique_ptr< juce::Component > > ownedComponents
BuildContext buildContext
bool showHeaderFlag = true
bool showFooterFlag = true
bool crashRecoveryEnabled = false
juce::File crashRecoveryFile
Static Private Attributes
static constexpr int headerHeight = 36
static constexpr int footerHeight = 22
static constexpr int autosaveIntervalMs = 10000
Detailed Description
Definition at line 27 of file DirektBaseEditor.h.
Constructor & Destructor Documentation
DirektBaseEditor() [1/2]
DirektDSP::DirektBaseEditor::DirektBaseEditor (juce::AudioProcessor & processor, juce::AudioProcessorValueTreeState & apvts, Service::PresetManager & presetManager, const PluginConfig & config, const NodeDescriptor & rootDescriptor)
Definition at line 81 of file DirektBaseEditor.cpp.
DirektBaseEditor() [2/2]
DirektDSP::DirektBaseEditor::DirektBaseEditor (juce::AudioProcessor & processor, juce::AudioProcessorValueTreeState & apvts, Service::PresetManager & presetManager, const juce::String & pluginName, juce::Colour accentColour, float aspectRatio, int defaultWidth, const std::vector< SectionDescriptor > & sectionDescriptors)
Definition at line 113 of file DirektBaseEditor.cpp.
~DirektBaseEditor()
DirektDSP::DirektBaseEditor::~DirektBaseEditor () override
Definition at line 136 of file DirektBaseEditor.cpp.
References crashRecoveryEnabled, and crashRecoveryFile.
Member Function Documentation
bindMeterSource()
void DirektDSP::DirektBaseEditor::bindMeterSource (const juce::String & sourceID, const std::atomic< float > * source)
Definition at line 297 of file DirektBaseEditor.cpp.
References buildContext, findComponentByID(), and DirektDSP::BuildContext::meterSources.
configureCrashRecovery()
void DirektDSP::DirektBaseEditor::configureCrashRecovery (const juce::String & pluginName) private
Definition at line 340 of file DirektBaseEditor.cpp.
References autosaveIntervalMs, crashRecoveryEnabled, crashRecoveryFile, and saveCrashRecoverySnapshot().
Referenced by initCommon().
findComponentByID()
juce::Component * DirektDSP::DirektBaseEditor::findComponentByID (const juce::String & id) const
Definition at line 274 of file DirektBaseEditor.cpp.
Referenced by bindMeterSource().
findSection()
DirektSection * DirektDSP::DirektBaseEditor::findSection (const juce::String & title) protected
Definition at line 248 of file DirektBaseEditor.cpp.
References builtSections.
hidePopup()
void DirektDSP::DirektBaseEditor::hidePopup () protected
Definition at line 265 of file DirektBaseEditor.cpp.
References DirektDSP::DirektPopupPanel::hide(), and popup.
initCommon()
void DirektDSP::DirektBaseEditor::initCommon (const juce::String & pluginName, juce::Colour accentColour, float ratio, int , int minWidth, int maxWidth, bool showHeader, bool showFooter, bool resizable, bool showTooltips) private
Definition at line 20 of file DirektBaseEditor.cpp.
References aspectRatio, configureCrashRecovery(), constrainer, footer, header, lookAndFeel, DirektDSP::DirektHeader::onPresetLabelClicked, popup, presetBrowser, presetManager, resizer, DirektDSP::DirektLookAndFeel::setAccentColour(), showFooterFlag, showHeaderFlag, showPopup(), tooltipWindow, and DirektDSP::DirektHeader::updatePresetName().
keyPressed()
bool DirektDSP::DirektBaseEditor::keyPressed (const juce::KeyPress & key) override
Handles editor-local undo/redo shortcuts for parameter edits.
Supported bindings:
Cmd/Ctrl + Z: undo
Cmd/Ctrl + Shift + Z: redo
Cmd/Ctrl + Y: redo
Definition at line 202 of file DirektBaseEditor.cpp.
References apvts, parameterHistory, DirektDSP::DirektParameterHistory::redo(), and DirektDSP::DirektParameterHistory::undo().
layoutCustomSections()
void DirektDSP::DirektBaseEditor::layoutCustomSections (juce::Rectangle< int > mainArea) protected virtual
Definition at line 225 of file DirektBaseEditor.cpp.
References builtSections.
Referenced by resized().
paint()
void DirektDSP::DirektBaseEditor::paint (juce::Graphics & g) override
Definition at line 148 of file DirektBaseEditor.cpp.
References DirektDSP::Colours::bgDark, footerHeight, headerHeight, paintCustomBackground(), showFooterFlag, and showHeaderFlag.
paintCustomBackground()
void DirektDSP::DirektBaseEditor::paintCustomBackground (juce::Graphics & g, juce::Rectangle< int > mainArea) protected virtual
Definition at line 243 of file DirektBaseEditor.cpp.
Referenced by paint().
resized()
void DirektDSP::DirektBaseEditor::resized () override
Definition at line 165 of file DirektBaseEditor.cpp.
References DirektDSP::BuiltNode::component, configDriven, footer, footerHeight, header, headerHeight, layoutCustomSections(), popup, resizer, rootBuiltNode, showFooterFlag, and showHeaderFlag.
restoreCrashRecoveryIfNeeded()
void DirektDSP::DirektBaseEditor::restoreCrashRecoveryIfNeeded () private
Definition at line 404 of file DirektBaseEditor.cpp.
References apvts, crashRecoveryFile, header, saveCrashRecoverySnapshot(), and DirektDSP::DirektHeader::updatePresetName().
saveCrashRecoverySnapshot()
void DirektDSP::DirektBaseEditor::saveCrashRecoverySnapshot () const private
Definition at line 382 of file DirektBaseEditor.cpp.
References apvts, crashRecoveryEnabled, and crashRecoveryFile.
Referenced by configureCrashRecovery(), restoreCrashRecoveryIfNeeded(), and timerCallback().
showPopup()
void DirektDSP::DirektBaseEditor::showPopup (const juce::String & title, juce::Component * content, int w, int h) protected
Definition at line 260 of file DirektBaseEditor.cpp.
References popup, and DirektDSP::DirektPopupPanel::show().
Referenced by initCommon().
timerCallback()
void DirektDSP::DirektBaseEditor::timerCallback () override private
Definition at line 448 of file DirektBaseEditor.cpp.
References saveCrashRecoverySnapshot().
Member Data Documentation
apvts
juce::AudioProcessorValueTreeState& DirektDSP::DirektBaseEditor::apvts protected
Definition at line 67 of file DirektBaseEditor.h.
Referenced by keyPressed(), restoreCrashRecoveryIfNeeded(), and saveCrashRecoverySnapshot().
aspectRatio
float DirektDSP::DirektBaseEditor::aspectRatio {} private
Definition at line 88 of file DirektBaseEditor.h.
Referenced by initCommon().
autosaveIntervalMs
constexpr int DirektDSP::DirektBaseEditor::autosaveIntervalMs = 10000 static constexpr private
Definition at line 105 of file DirektBaseEditor.h.
Referenced by configureCrashRecovery().
buildContext
BuildContext DirektDSP::DirektBaseEditor::buildContext private
Definition at line 97 of file DirektBaseEditor.h.
Referenced by bindMeterSource().
builtSections
std::vector<BuiltSection> DirektDSP::DirektBaseEditor::builtSections protected
Definition at line 68 of file DirektBaseEditor.h.
Referenced by findSection(), and layoutCustomSections().
configDriven
bool DirektDSP::DirektBaseEditor::configDriven = false private
Definition at line 93 of file DirektBaseEditor.h.
Referenced by resized().
constrainer
juce::ComponentBoundsConstrainer DirektDSP::DirektBaseEditor::constrainer private
Definition at line 85 of file DirektBaseEditor.h.
Referenced by initCommon().
crashRecoveryEnabled
bool DirektDSP::DirektBaseEditor::crashRecoveryEnabled = false private
Definition at line 100 of file DirektBaseEditor.h.
Referenced by configureCrashRecovery(), saveCrashRecoverySnapshot(), and ~DirektBaseEditor().
crashRecoveryFile
juce::File DirektDSP::DirektBaseEditor::crashRecoveryFile private
Definition at line 101 of file DirektBaseEditor.h.
Referenced by configureCrashRecovery(), restoreCrashRecoveryIfNeeded(), saveCrashRecoverySnapshot(), and ~DirektBaseEditor().
footer
DirektFooter DirektDSP::DirektBaseEditor::footer private
Definition at line 80 of file DirektBaseEditor.h.
Referenced by initCommon(), and resized().
footerHeight
constexpr int DirektDSP::DirektBaseEditor::footerHeight = 22 static constexpr private
Definition at line 104 of file DirektBaseEditor.h.
Referenced by paint(), and resized().
header
DirektHeader DirektDSP::DirektBaseEditor::header private
Definition at line 79 of file DirektBaseEditor.h.
Referenced by initCommon(), resized(), and restoreCrashRecoveryIfNeeded().
headerHeight
constexpr int DirektDSP::DirektBaseEditor::headerHeight = 36 static constexpr private
Definition at line 103 of file DirektBaseEditor.h.
Referenced by paint(), and resized().
lookAndFeel
DirektLookAndFeel DirektDSP::DirektBaseEditor::lookAndFeel private
Definition at line 78 of file DirektBaseEditor.h.
Referenced by initCommon().
ownedComponents
std::vector<std::unique_ptr<juce::Component> > DirektDSP::DirektBaseEditor::ownedComponents private
Definition at line 96 of file DirektBaseEditor.h.
parameterHistory
DirektParameterHistory DirektDSP::DirektBaseEditor::parameterHistory private
Definition at line 94 of file DirektBaseEditor.h.
Referenced by keyPressed().
popup
DirektPopupPanel DirektDSP::DirektBaseEditor::popup private
Definition at line 81 of file DirektBaseEditor.h.
Referenced by hidePopup(), initCommon(), resized(), and showPopup().
presetBrowser
std::unique_ptr<DirektPresetBrowser> DirektDSP::DirektBaseEditor::presetBrowser private
Definition at line 90 of file DirektBaseEditor.h.
Referenced by initCommon().
presetManager
Service::PresetManager& DirektDSP::DirektBaseEditor::presetManager private
Definition at line 89 of file DirektBaseEditor.h.
Referenced by initCommon().
resizer
std::unique_ptr<juce::ResizableCornerComponent> DirektDSP::DirektBaseEditor::resizer private
Definition at line 86 of file DirektBaseEditor.h.
Referenced by initCommon(), and resized().
rootBuiltNode
BuiltNode DirektDSP::DirektBaseEditor::rootBuiltNode private
Definition at line 95 of file DirektBaseEditor.h.
Referenced by resized().
showFooterFlag
bool DirektDSP::DirektBaseEditor::showFooterFlag = true private
Definition at line 99 of file DirektBaseEditor.h.
Referenced by initCommon(), paint(), and resized().
showHeaderFlag
bool DirektDSP::DirektBaseEditor::showHeaderFlag = true private
Definition at line 98 of file DirektBaseEditor.h.
Referenced by initCommon(), paint(), and resized().
tooltipWindow
std::unique_ptr<juce::TooltipWindow> DirektDSP::DirektBaseEditor::tooltipWindow private
Definition at line 83 of file DirektBaseEditor.h.
Referenced by initCommon().
The documentation for this class was generated from the following files:
core/DirektBaseEditor.h
core/DirektBaseEditor.cpp