DirektDSP GUI: DirektDSP::DirektPresetBrowser Class Reference
DirektDSP::DirektPresetBrowser Class Reference
#include <DirektPresetBrowser.h>
Classes
class CategoryListModel
struct PresetEntry
class PresetListModel
Public Member Functions
DirektPresetBrowser (Service::PresetManager &pm, juce::Colour accentColour)
Creates preset browser bound to preset manager.
void resized () override
void paint (juce::Graphics &g) override
void visibilityChanged () override
Public Attributes
std::function< void()> onPresetLoaded
Private Member Functions
void refreshTags ()
Rebuilds visible filter tags from preset metadata and favorites state.
void refreshCategories ()
Rebuilds preset list using active tag and full-text query filters.
void refreshPresets ()
void onCategorySelected ()
Handles user selecting a tag/category row in sidebar.
void onPresetSelected ()
Handles user selecting preset row and loads it.
void onSearchTextChanged ()
Updates full-text search filter and refreshes results.
void onFavoriteToggleRequested (int row)
Toggles favorite state for selected preset row.
void doSave ()
Opens modal flow for saving current state as new preset.
void doDelete ()
Opens modal flow for deleting selected preset.
void doMove ()
Opens modal flow for moving selected preset to other category.
void doNewCategory ()
Opens modal flow for creating new category/tag bucket.
void loadFavorites ()
Loads persisted favorites from user settings storage.
void saveFavorites () const
Saves current favorites set to user settings storage.
bool isFavorite (const PresetEntry &entry) const
Returns true if preset currently marked as favorite.
Static Private Member Functions
static juce::String makeFavoriteKey (const juce::String &name, const juce::String &category)
Builds stable key for favorite persistence lookups.
Private Attributes
Service::PresetManager & presetManager
juce::Colour accent
CategoryListModel categoryModel
juce::ListBox categoryList {"Categories", &categoryModel}
PresetListModel presetModel
juce::ListBox presetList {"Presets", &presetModel}
juce::TextEditor searchEditor
juce::TextButton saveBtn {"Save"}
juce::TextButton deleteBtn {"Delete"}
juce::TextButton moveBtn {"Move"}
juce::TextButton newCatBtn {"New Category"}
std::unordered_set< std::string > favoritePresetKeys
Detailed Description
Definition at line 18 of file DirektPresetBrowser.h.
Constructor & Destructor Documentation
DirektPresetBrowser()
DirektDSP::DirektPresetBrowser::DirektPresetBrowser (Service::PresetManager & pm, juce::Colour accentColour)
Creates preset browser bound to preset manager.
Parameters
pm Preset service used for list/load/save operations.
accentColour Accent colour used for highlighted controls.
Definition at line 91 of file DirektPresetBrowser.cpp.
References accent, DirektDSP::DirektPresetBrowser::CategoryListModel::accent, DirektDSP::DirektPresetBrowser::PresetListModel::accent, DirektDSP::Colours::bgPanel, DirektDSP::Colours::bgSection, categoryList, categoryModel, deleteBtn, doDelete(), doMove(), doNewCategory(), doSave(), isFavorite(), DirektDSP::DirektPresetBrowser::PresetListModel::isFavorite, loadFavorites(), moveBtn, newCatBtn, onCategorySelected(), DirektDSP::DirektPresetBrowser::PresetListModel::onFavoriteToggle, onFavoriteToggleRequested(), onPresetSelected(), onSearchTextChanged(), DirektDSP::DirektPresetBrowser::CategoryListModel::onSelectionChanged, DirektDSP::DirektPresetBrowser::PresetListModel::onSelectionChanged, presetList, presetModel, saveBtn, searchEditor, DirektDSP::Colours::textBright, and DirektDSP::Colours::textDim.
Member Function Documentation
doDelete()
void DirektDSP::DirektPresetBrowser::doDelete () private
Opens modal flow for deleting selected preset.
Definition at line 367 of file DirektPresetBrowser.cpp.
Referenced by DirektPresetBrowser().
doMove()
void DirektDSP::DirektPresetBrowser::doMove () private
Opens modal flow for moving selected preset to other category.
Definition at line 406 of file DirektPresetBrowser.cpp.
Referenced by DirektPresetBrowser().
doNewCategory()
void DirektDSP::DirektPresetBrowser::doNewCategory () private
Opens modal flow for creating new category/tag bucket.
Definition at line 451 of file DirektPresetBrowser.cpp.
Referenced by DirektPresetBrowser().
doSave()
void DirektDSP::DirektPresetBrowser::doSave () private
Opens modal flow for saving current state as new preset.
Definition at line 332 of file DirektPresetBrowser.cpp.
References Service::PresetManager::getCurrentCategory(), and presetManager.
Referenced by DirektPresetBrowser().
isFavorite()
bool DirektDSP::DirektPresetBrowser::isFavorite (const PresetEntry & entry) const private
Returns true if preset currently marked as favorite.
Definition at line 481 of file DirektPresetBrowser.cpp.
References DirektDSP::DirektPresetBrowser::PresetEntry::category, and DirektDSP::DirektPresetBrowser::PresetEntry::name.
Referenced by DirektPresetBrowser(), and DirektDSP::DirektPresetBrowser::PresetListModel::paintListBoxItem().
loadFavorites()
void DirektDSP::DirektPresetBrowser::loadFavorites () private
Loads persisted favorites from user settings storage.
Definition at line 487 of file DirektPresetBrowser.cpp.
Referenced by DirektPresetBrowser().
makeFavoriteKey()
juce::String DirektDSP::DirektPresetBrowser::makeFavoriteKey (const juce::String & name, const juce::String & category) static private
Builds stable key for favorite persistence lookups.
Definition at line 476 of file DirektPresetBrowser.cpp.
Referenced by onFavoriteToggleRequested(), and refreshPresets().
onCategorySelected()
void DirektDSP::DirektPresetBrowser::onCategorySelected () private
Handles user selecting a tag/category row in sidebar.
Definition at line 271 of file DirektPresetBrowser.cpp.
References categoryList, categoryModel, refreshPresets(), and DirektDSP::DirektPresetBrowser::CategoryListModel::selectedRow.
Referenced by DirektPresetBrowser().
onFavoriteToggleRequested()
void DirektDSP::DirektPresetBrowser::onFavoriteToggleRequested (int row) private
Toggles favorite state for selected preset row.
Definition at line 304 of file DirektPresetBrowser.cpp.
References DirektDSP::DirektPresetBrowser::CategoryListModel::categories, categoryModel, favoritePresetKeys, makeFavoriteKey(), presetList, presetModel, DirektDSP::DirektPresetBrowser::PresetListModel::presets, refreshPresets(), refreshTags(), saveFavorites(), and DirektDSP::DirektPresetBrowser::CategoryListModel::selectedRow.
Referenced by DirektPresetBrowser().
onPresetSelected()
void DirektDSP::DirektPresetBrowser::onPresetSelected () private
Handles user selecting preset row and loads it.
Definition at line 279 of file DirektPresetBrowser.cpp.
References Service::PresetManager::loadPreset(), onPresetLoaded, presetList, presetManager, presetModel, DirektDSP::DirektPresetBrowser::PresetListModel::presets, and DirektDSP::DirektPresetBrowser::PresetListModel::selectedRow.
Referenced by DirektPresetBrowser().
onSearchTextChanged()
void DirektDSP::DirektPresetBrowser::onSearchTextChanged () private
Updates full-text search filter and refreshes results.
Definition at line 299 of file DirektPresetBrowser.cpp.
References refreshPresets().
Referenced by DirektPresetBrowser().
paint()
void DirektDSP::DirektPresetBrowser::paint (juce::Graphics & g) override
Definition at line 147 of file DirektPresetBrowser.cpp.
References DirektDSP::Colours::bgPanel.
refreshCategories()
void DirektDSP::DirektPresetBrowser::refreshCategories () private
Rebuilds preset list using active tag and full-text query filters.
Definition at line 176 of file DirektPresetBrowser.cpp.
References refreshTags().
Referenced by visibilityChanged().
refreshPresets()
void DirektDSP::DirektPresetBrowser::refreshPresets () private
Definition at line 211 of file DirektPresetBrowser.cpp.
References DirektDSP::DirektPresetBrowser::CategoryListModel::categories, categoryList, categoryModel, favoritePresetKeys, Service::PresetManager::getAllPresetMetadata(), makeFavoriteKey(), presetList, presetManager, presetModel, DirektDSP::DirektPresetBrowser::PresetListModel::presets, searchEditor, and DirektDSP::DirektPresetBrowser::PresetListModel::selectedRow.
Referenced by onCategorySelected(), onFavoriteToggleRequested(), onSearchTextChanged(), and visibilityChanged().
refreshTags()
void DirektDSP::DirektPresetBrowser::refreshTags () private
Rebuilds visible filter tags from preset metadata and favorites state.
Definition at line 181 of file DirektPresetBrowser.cpp.
References DirektDSP::DirektPresetBrowser::CategoryListModel::categories, categoryList, categoryModel, Service::PresetManager::getAllPresetMetadata(), presetManager, and DirektDSP::DirektPresetBrowser::CategoryListModel::selectedRow.
Referenced by onFavoriteToggleRequested(), and refreshCategories().
resized()
void DirektDSP::DirektPresetBrowser::resized () override
Definition at line 152 of file DirektPresetBrowser.cpp.
References categoryList, deleteBtn, moveBtn, newCatBtn, presetList, saveBtn, and searchEditor.
saveFavorites()
void DirektDSP::DirektPresetBrowser::saveFavorites () const private
Saves current favorites set to user settings storage.
Definition at line 517 of file DirektPresetBrowser.cpp.
Referenced by onFavoriteToggleRequested().
visibilityChanged()
void DirektDSP::DirektPresetBrowser::visibilityChanged () override
Definition at line 138 of file DirektPresetBrowser.cpp.
References refreshCategories(), and refreshPresets().
Member Data Documentation
accent
juce::Colour DirektDSP::DirektPresetBrowser::accent private
Definition at line 69 of file DirektPresetBrowser.h.
Referenced by DirektPresetBrowser(), and DirektDSP::DirektPresetBrowser::PresetListModel::paintListBoxItem().
categoryList
juce::ListBox DirektDSP::DirektPresetBrowser::categoryList {"Categories", &categoryModel} private
Definition at line 92 of file DirektPresetBrowser.h.
Referenced by DirektPresetBrowser(), onCategorySelected(), refreshPresets(), refreshTags(), and resized().
categoryModel
CategoryListModel DirektDSP::DirektPresetBrowser::categoryModel private
Definition at line 91 of file DirektPresetBrowser.h.
Referenced by DirektPresetBrowser(), onCategorySelected(), onFavoriteToggleRequested(), refreshPresets(), and refreshTags().
deleteBtn
juce::TextButton DirektDSP::DirektPresetBrowser::deleteBtn {"Delete"} private
Definition at line 124 of file DirektPresetBrowser.h.
Referenced by DirektPresetBrowser(), and resized().
favoritePresetKeys
std::unordered_set<std::string> DirektDSP::DirektPresetBrowser::favoritePresetKeys private
Definition at line 127 of file DirektPresetBrowser.h.
Referenced by onFavoriteToggleRequested(), and refreshPresets().
moveBtn
juce::TextButton DirektDSP::DirektPresetBrowser::moveBtn {"Move"} private
Definition at line 125 of file DirektPresetBrowser.h.
Referenced by DirektPresetBrowser(), and resized().
newCatBtn
juce::TextButton DirektDSP::DirektPresetBrowser::newCatBtn {"New Category"} private
Definition at line 126 of file DirektPresetBrowser.h.
Referenced by DirektPresetBrowser(), and resized().
onPresetLoaded
std::function<void()> DirektDSP::DirektPresetBrowser::onPresetLoaded
Definition at line 32 of file DirektPresetBrowser.h.
Referenced by onPresetSelected().
presetList
juce::ListBox DirektDSP::DirektPresetBrowser::presetList {"Presets", &presetModel} private
Definition at line 119 of file DirektPresetBrowser.h.
Referenced by DirektPresetBrowser(), onFavoriteToggleRequested(), onPresetSelected(), refreshPresets(), and resized().
presetManager
Service::PresetManager& DirektDSP::DirektPresetBrowser::presetManager private
Definition at line 68 of file DirektPresetBrowser.h.
Referenced by doSave(), onPresetSelected(), refreshPresets(), and refreshTags().
presetModel
PresetListModel DirektDSP::DirektPresetBrowser::presetModel private
Definition at line 118 of file DirektPresetBrowser.h.
Referenced by DirektPresetBrowser(), onFavoriteToggleRequested(), onPresetSelected(), and refreshPresets().
saveBtn
juce::TextButton DirektDSP::DirektPresetBrowser::saveBtn {"Save"} private
Definition at line 123 of file DirektPresetBrowser.h.
Referenced by DirektPresetBrowser(), and resized().
searchEditor
juce::TextEditor DirektDSP::DirektPresetBrowser::searchEditor private
Definition at line 120 of file DirektPresetBrowser.h.
Referenced by DirektPresetBrowser(), refreshPresets(), and resized().
The documentation for this class was generated from the following files:
chrome/DirektPresetBrowser.h
chrome/DirektPresetBrowser.cpp