DirektDSP GUI: Service::PresetManager Class Reference
Service::PresetManager Class Reference abstract
#include <PresetManager.h>
Public Member Functions
virtual ~PresetManager ()=default
virtual juce::String getCurrentPreset () const =0
virtual juce::String getCurrentCategory () const =0
virtual void loadPreset (const juce::String &name, const juce::String &category)=0
virtual void loadPreviousPreset ()=0
virtual void loadNextPreset ()=0
virtual void savePreset (const juce::String &name, const juce::String &artist, const juce::String &category)=0
virtual void deletePreset (const juce::String &name, const juce::String &category)=0
virtual void movePresetToCategory (const juce::String &name, const juce::String &fromCategory, const juce::String &toCategory)=0
virtual void createCategory (const juce::String &name)=0
virtual juce::StringArray getAllCategories () const =0
virtual std::vector< PresetMetadata > getAllPresetMetadata () const =0
virtual std::vector< PresetMetadata > getPresetMetadataInCategory (const juce::String &category) const =0
Detailed Description
Definition at line 28 of file PresetManager.h.
Constructor & Destructor Documentation
~PresetManager()
virtual Service::PresetManager::~PresetManager () virtual default
Member Function Documentation
createCategory()
virtual void Service::PresetManager::createCategory (const juce::String & name) pure virtual
Implemented in StandaloneTestProcessor::GalleryPresetManager.
deletePreset()
virtual void Service::PresetManager::deletePreset (const juce::String & name, const juce::String & category) pure virtual
Implemented in StandaloneTestProcessor::GalleryPresetManager.
getAllCategories()
virtual juce::StringArray Service::PresetManager::getAllCategories () const pure virtual
Implemented in StandaloneTestProcessor::GalleryPresetManager.
getAllPresetMetadata()
virtual std::vector< PresetMetadata > Service::PresetManager::getAllPresetMetadata () const pure virtual
Implemented in StandaloneTestProcessor::GalleryPresetManager.
Referenced by DirektDSP::DirektPresetBrowser::refreshPresets(), and DirektDSP::DirektPresetBrowser::refreshTags().
getCurrentCategory()
virtual juce::String Service::PresetManager::getCurrentCategory () const pure virtual
Implemented in StandaloneTestProcessor::GalleryPresetManager.
Referenced by DirektDSP::DirektPresetBrowser::doSave().
getCurrentPreset()
virtual juce::String Service::PresetManager::getCurrentPreset () const pure virtual
Implemented in StandaloneTestProcessor::GalleryPresetManager.
Referenced by DirektDSP::DirektHeader::updatePresetName().
getPresetMetadataInCategory()
virtual std::vector< PresetMetadata > Service::PresetManager::getPresetMetadataInCategory (const juce::String & category) const pure virtual
Implemented in StandaloneTestProcessor::GalleryPresetManager.
loadNextPreset()
virtual void Service::PresetManager::loadNextPreset () pure virtual
Implemented in StandaloneTestProcessor::GalleryPresetManager.
Referenced by DirektDSP::DirektHeader::DirektHeader().
loadPreset()
virtual void Service::PresetManager::loadPreset (const juce::String & name, const juce::String & category) pure virtual
Implemented in StandaloneTestProcessor::GalleryPresetManager.
Referenced by DirektDSP::DirektPresetBrowser::onPresetSelected().
loadPreviousPreset()
virtual void Service::PresetManager::loadPreviousPreset () pure virtual
Implemented in StandaloneTestProcessor::GalleryPresetManager.
Referenced by DirektDSP::DirektHeader::DirektHeader().
movePresetToCategory()
virtual void Service::PresetManager::movePresetToCategory (const juce::String & name, const juce::String & fromCategory, const juce::String & toCategory) pure virtual
Implemented in StandaloneTestProcessor::GalleryPresetManager.
savePreset()
virtual void Service::PresetManager::savePreset (const juce::String & name, const juce::String & artist, const juce::String & category) pure virtual
Implemented in StandaloneTestProcessor::GalleryPresetManager.
The documentation for this class was generated from the following file:
Service/PresetManager.h