DirektDSP GUI: DirektDSP::DirektTabPanel Class Reference
DirektDSP::DirektTabPanel Class Reference
#include <DirektTabPanel.h>
Classes
struct TabEntry
Public Member Functions
DirektTabPanel (juce::Colour accentColour)
void addTab (const juce::String &label, juce::Component *content)
void setActiveTab (int index)
void paint (juce::Graphics &g) override
void resized () override
Private Member Functions
void updateVisibility ()
Private Attributes
juce::Colour accent
std::vector< TabEntry > tabs
std::vector< std::unique_ptr< juce::TextButton > > tabButtons
int activeIndex = 0
Static Private Attributes
static constexpr int tabBarHeight = 28
Detailed Description
Definition at line 11 of file DirektTabPanel.h.
Constructor & Destructor Documentation
DirektTabPanel()
DirektDSP::DirektTabPanel::DirektTabPanel (juce::Colour accentColour) explicit
Definition at line 6 of file DirektTabPanel.cpp.
Member Function Documentation
addTab()
void DirektDSP::DirektTabPanel::addTab (const juce::String & label, juce::Component * content)
Definition at line 8 of file DirektTabPanel.cpp.
References DirektDSP::Colours::bgSection, setActiveTab(), tabButtons, tabs, DirektDSP::Colours::textDim, and updateVisibility().
paint()
void DirektDSP::DirektTabPanel::paint (juce::Graphics & g) override
Definition at line 52 of file DirektTabPanel.cpp.
References accent, activeIndex, DirektDSP::Colours::bgHeader, tabBarHeight, and tabButtons.
resized()
void DirektDSP::DirektTabPanel::resized () override
Definition at line 69 of file DirektTabPanel.cpp.
References tabBarHeight, tabButtons, and tabs.
Referenced by setActiveTab().
setActiveTab()
void DirektDSP::DirektTabPanel::setActiveTab (int index)
Definition at line 24 of file DirektTabPanel.cpp.
References activeIndex, resized(), tabs, and updateVisibility().
Referenced by addTab().
updateVisibility()
void DirektDSP::DirektTabPanel::updateVisibility () private
Definition at line 37 of file DirektTabPanel.cpp.
References accent, activeIndex, tabButtons, tabs, and DirektDSP::Colours::textDim.
Referenced by addTab(), and setActiveTab().
Member Data Documentation
accent
juce::Colour DirektDSP::DirektTabPanel::accent private
Definition at line 29 of file DirektTabPanel.h.
Referenced by paint(), and updateVisibility().
activeIndex
int DirektDSP::DirektTabPanel::activeIndex = 0 private
Definition at line 32 of file DirektTabPanel.h.
Referenced by paint(), setActiveTab(), and updateVisibility().
tabBarHeight
constexpr int DirektDSP::DirektTabPanel::tabBarHeight = 28 static constexpr private
Definition at line 34 of file DirektTabPanel.h.
Referenced by paint(), and resized().
tabButtons
std::vector<std::unique_ptr<juce::TextButton> > DirektDSP::DirektTabPanel::tabButtons private
Definition at line 31 of file DirektTabPanel.h.
Referenced by addTab(), paint(), resized(), and updateVisibility().
tabs
std::vector<TabEntry> DirektDSP::DirektTabPanel::tabs private
Definition at line 30 of file DirektTabPanel.h.
Referenced by addTab(), resized(), setActiveTab(), and updateVisibility().
The documentation for this class was generated from the following files:
layout/DirektTabPanel.h
layout/DirektTabPanel.cpp