DirektDSP GUI: DirektDSP::DirektFlexContainer Class Reference
DirektDSP::DirektFlexContainer Class Reference
#include <DirektFlexContainer.h>
Classes
struct ChildEntry
Public Types
enum class Direction { Row , Column }
Public Member Functions
DirektFlexContainer (Direction dir)
void addFlexChild (juce::Component *child, const SizeHint &hint={})
void resized () override
void paintOverChildren (juce::Graphics &g) override
void enableDragReorder (bool enable)
Enable or disable drag-to-reorder for DirektSection children.
Private Member Functions
void setupSectionDragCallbacks (DirektSection *section)
void clearSectionDragCallbacks (DirektSection *section)
void handleDragMoved (DirektSection *section, juce::Point< int > screenPos)
void handleDragEnded (DirektSection *section)
int getDropIndexFromPosition (juce::Point< int > localPos) const
Private Attributes
Direction direction
std::vector< ChildEntry > entries
bool dragReorderEnabled = false
int draggedIndex = -1
int dropTargetIndex = -1
Detailed Description
Definition at line 13 of file DirektFlexContainer.h.
Member Enumeration Documentation
Direction
enum class DirektDSP::DirektFlexContainer::Direction strong
Enumerator
Row
Column
Definition at line 16 of file DirektFlexContainer.h.
Constructor & Destructor Documentation
DirektFlexContainer()
DirektDSP::DirektFlexContainer::DirektFlexContainer (Direction dir) explicit
Definition at line 8 of file DirektFlexContainer.cpp.
Member Function Documentation
addFlexChild()
void DirektDSP::DirektFlexContainer::addFlexChild (juce::Component * child, const SizeHint & hint = {})
Definition at line 10 of file DirektFlexContainer.cpp.
References dragReorderEnabled, entries, and setupSectionDragCallbacks().
clearSectionDragCallbacks()
void DirektDSP::DirektFlexContainer::clearSectionDragCallbacks (DirektSection * section) private
Definition at line 126 of file DirektFlexContainer.cpp.
References DirektDSP::DirektSection::onDragEnded, DirektDSP::DirektSection::onDragMoved, and DirektDSP::DirektSection::setDraggable().
Referenced by enableDragReorder().
enableDragReorder()
void DirektDSP::DirektFlexContainer::enableDragReorder (bool enable)
Enable or disable drag-to-reorder for DirektSection children.
When enabled, each DirektSection child receives a drag handle in its title bar and the container shows a drop-position indicator while the user drags. Only meaningful for Column-direction containers.
Definition at line 95 of file DirektFlexContainer.cpp.
References clearSectionDragCallbacks(), dragReorderEnabled, entries, and setupSectionDragCallbacks().
getDropIndexFromPosition()
int DirektDSP::DirektFlexContainer::getDropIndexFromPosition (juce::Point< int > localPos) const private
Definition at line 187 of file DirektFlexContainer.cpp.
References entries.
Referenced by handleDragMoved().
handleDragEnded()
void DirektDSP::DirektFlexContainer::handleDragEnded (DirektSection * section) private
Definition at line 151 of file DirektFlexContainer.cpp.
References draggedIndex, dropTargetIndex, entries, and resized().
Referenced by setupSectionDragCallbacks().
handleDragMoved()
void DirektDSP::DirektFlexContainer::handleDragMoved (DirektSection * section, juce::Point< int > screenPos) private
Definition at line 133 of file DirektFlexContainer.cpp.
References draggedIndex, dropTargetIndex, entries, and getDropIndexFromPosition().
Referenced by setupSectionDragCallbacks().
paintOverChildren()
void DirektDSP::DirektFlexContainer::paintOverChildren (juce::Graphics & g) override
Definition at line 60 of file DirektFlexContainer.cpp.
References draggedIndex, dropTargetIndex, and entries.
resized()
void DirektDSP::DirektFlexContainer::resized () override
Definition at line 24 of file DirektFlexContainer.cpp.
References direction, entries, and Row.
Referenced by handleDragEnded().
setupSectionDragCallbacks()
void DirektDSP::DirektFlexContainer::setupSectionDragCallbacks (DirektSection * section) private
Definition at line 117 of file DirektFlexContainer.cpp.
References handleDragEnded(), handleDragMoved(), DirektDSP::DirektSection::onDragEnded, DirektDSP::DirektSection::onDragMoved, and DirektDSP::DirektSection::setDraggable().
Referenced by addFlexChild(), and enableDragReorder().
Member Data Documentation
direction
Direction DirektDSP::DirektFlexContainer::direction private
Definition at line 38 of file DirektFlexContainer.h.
Referenced by resized().
draggedIndex
int DirektDSP::DirektFlexContainer::draggedIndex = -1 private
Definition at line 50 of file DirektFlexContainer.h.
Referenced by handleDragEnded(), handleDragMoved(), and paintOverChildren().
dragReorderEnabled
bool DirektDSP::DirektFlexContainer::dragReorderEnabled = false private
Definition at line 49 of file DirektFlexContainer.h.
Referenced by addFlexChild(), and enableDragReorder().
dropTargetIndex
int DirektDSP::DirektFlexContainer::dropTargetIndex = -1 private
Definition at line 51 of file DirektFlexContainer.h.
Referenced by handleDragEnded(), handleDragMoved(), and paintOverChildren().
entries
std::vector<ChildEntry> DirektDSP::DirektFlexContainer::entries private
Definition at line 46 of file DirektFlexContainer.h.
Referenced by addFlexChild(), enableDragReorder(), getDropIndexFromPosition(), handleDragEnded(), handleDragMoved(), paintOverChildren(), and resized().
The documentation for this class was generated from the following files:
layout/DirektFlexContainer.h
layout/DirektFlexContainer.cpp